os:
  - linux
  - osx
  - windows
dist: xenial
language: node_js
node_js:
  - node
  - lts/*
script:
  - cp src/js/config.js.dist src/js/config.js
  - npm run build
after_success:
  - git config --global user.name "ricki-z"
  - git config --global user.email "ricki_z@gmx.de"
  - git remote rm origin
  - git remote add origin https://ricki-z:${GH_TOKEN}@github.com/opendata-stuttgart/feinstaub-map.git
  - npm run ghpages
